### ISSUE TITLE
Android release builds

### ISSUE THREAD

**Issue by rtm516** [shevek/jarjar#15]
This plugin doesn't work when doing a release build for an android app, I get the below error which is not present on a normal debug build.
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:collectReleaseDependencies'.
> java.io.FileNotFoundException: GeyserAndroid\app\build\jarjar (Access is denied)
```
It displays slightly different on Linux
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:collectReleaseDependencies'.
> java.io.FileNotFoundException: GeyserAndroid/app/build/jarjar (Is a directory)
```
Project: https://github.com/rtm516/GeyserAndroid/

**Comment by InsaneWaifu** [comment]
This is basically the signing error i warned on your project. I'm not sure but maybe building a fully unsigned apk then signing it manually with a external tool might work

Edit: That doesn't work because with plain old assemble it still throws the error

**Comment by rtm516** [comment]
> This is basically the signing error i warned on your project. I'm not sure but maybe building a fully unsigned apk then signing it manually with a external tool might work
> 
> Edit: That doesn't work because with plain old assemble it still throws the error

Forgot about the issue opened on that project, but its better to have it logged here. If there is another plugin I can use instead of this that would be great, see https://stackoverflow.com/questions/62866972/ for more info.

**Comment by InsaneWaifu** [comment]
Yeah i found out about your project from that SO thread

**Comment by rtm516** [comment]
I found a fix to this, see https://github.com/rtm516/GeyserAndroid/commit/6703c7febc83ffe21e1f22f88bde8e5c3f4970f3#diff-39e7d8c00954e920b98e7636f0ac30b2

**Comment by InsaneWaifu** [comment]
Makes sense why that would fix it. I was digging around in AOSP gradle plugin for an answer but I couldn't find one. You are a lifesaver! I'm dying to use this but I fucked up my Linux because I read on SF that rm -rf doesn't follow symlinks...
